name: check-for-attribution
run-name: Checking ${{ github.action }}'s push for suitable attribution
on: [push]
jobs:
  check-for-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "ATTRIBUTION.md"