name: check-for-attribution
run-name: Checking ${{ github.event.head_commit.author.name }}'s push for suitable attribution
on: [push]
jobs:
  check-for-file:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github) }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "*/AUTHORS.txt"
          fail: true

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|${{ github.event.repository.name }}> - user
           ${{ github.event.head_commit.author.name }} has not included an AUTHORS.txt file"
          footer: ''
          notification_title: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
